/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  about: () => import("@/views/about/index.vue"),
  gen_database: () => import("@/views/gen/database/index.vue"),
  gen_template: () => import("@/views/gen/template/index.vue"),
  home: () => import("@/views/home/index.vue"),
  setting_app: () => import("@/views/setting/app/index.vue"),
  setting_configure: () => import("@/views/setting/configure/index.vue"),
  setting_department: () => import("@/views/setting/department/index.vue"),
  setting_dict: () => import("@/views/setting/dict/index.vue"),
  setting_menu: () => import("@/views/setting/menu/index.vue"),
  setting_post: () => import("@/views/setting/post/index.vue"),
  setting_region: () => import("@/views/setting/region/index.vue"),
  setting_role: () => import("@/views/setting/role/index.vue"),
  setting_user: () => import("@/views/setting/user/index.vue"),
  "user-center": () => import("@/views/user-center/index.vue"),
};
