/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about',
      i18nKey: 'route.about',
      icon: 'fluent:book-information-24-regular',
      order: 0
    }
  },
  {
    name: 'gen',
    path: '/gen',
    component: 'layout.base',
    meta: {
      title: 'gen',
      i18nKey: 'route.gen',
      icon: 'hugeicons:source-code-square',
      order: 9
    },
    children: [
      {
        name: 'gen_database',
        path: '/gen/database',
        component: 'view.gen_database',
        meta: {
          title: 'gen_database',
          i18nKey: 'route.gen_database',
          icon: 'material-symbols-light:database',
          order: 100
        }
      },
      {
        name: 'gen_template',
        path: '/gen/template',
        component: 'view.gen_template',
        meta: {
          title: 'gen_template',
          i18nKey: 'route.gen_template',
          icon: 'tabler:template',
          order: 90
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 100
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|reset-pwd|code-login)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'setting',
    path: '/setting',
    component: 'layout.base',
    meta: {
      title: 'setting',
      i18nKey: 'route.setting',
      localIcon: 'menu-swagger',
      order: 10
    },
    children: [
      {
        name: 'setting_app',
        path: '/setting/app',
        component: 'view.setting_app',
        meta: {
          title: 'setting_app',
          i18nKey: 'route.setting_app',
          localIcon: 'menu-goods-list',
          order: 50
        }
      },
      {
        name: 'setting_configure',
        path: '/setting/configure',
        component: 'view.setting_configure',
        meta: {
          title: 'setting_configure',
          i18nKey: 'route.setting_configure',
          localIcon: 'menu-component',
          order: 70
        }
      },
      {
        name: 'setting_department',
        path: '/setting/department',
        component: 'view.setting_department',
        meta: {
          title: 'setting_department',
          i18nKey: 'route.setting_department',
          icon: 'ep:wind-power',
          order: 40
        }
      },
      {
        name: 'setting_dict',
        path: '/setting/dict',
        component: 'view.setting_dict',
        meta: {
          title: 'setting_dict',
          i18nKey: 'route.setting_dict',
          icon: 'ep:list',
          order: 30
        }
      },
      {
        name: 'setting_menu',
        path: '/setting/menu',
        component: 'view.setting_menu',
        meta: {
          title: 'setting_menu',
          i18nKey: 'route.setting_menu',
          icon: 'ep:menu',
          order: 20
        }
      },
      {
        name: 'setting_post',
        path: '/setting/post',
        component: 'view.setting_post',
        meta: {
          title: 'setting_post',
          i18nKey: 'route.setting_post',
          localIcon: 'menu-uv',
          order: 80
        }
      },
      {
        name: 'setting_region',
        path: '/setting/region',
        component: 'view.setting_region',
        meta: {
          title: 'setting_region',
          i18nKey: 'route.setting_region',
          localIcon: 'menu-textarea',
          order: 10
        }
      },
      {
        name: 'setting_role',
        path: '/setting/role',
        component: 'view.setting_role',
        meta: {
          title: 'setting_role',
          i18nKey: 'route.setting_role',
          localIcon: 'menu-role',
          order: 60
        }
      },
      {
        name: 'setting_user',
        path: '/setting/user',
        component: 'view.setting_user',
        meta: {
          title: 'setting_user',
          i18nKey: 'route.setting_user',
          icon: 'ep:user',
          order: 90
        }
      }
    ]
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      hideInMenu: true,
      icon: 'ph:user',
      activeMenu: 'home'
    }
  }
];
