name: Publish package to the Maven Central Repository
on:
  push:
    tags:
      - v*
env:
  PROJECT_DIR: panshi/aizuda-framework 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        working-directory: ${{ env.PROJECT_DIR }}
        run: chmod +x gradlew

      - name: Build without tests
        working-directory: ${{ env.PROJECT_DIR }}
        run: ./gradlew build -x test

      - name: Publish package to maven central
        working-directory: ${{ env.PROJECT_DIR }}
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_PASSPHRASE }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_SECRET_KEY }}
        run: ./gradlew publishAllPublicationsToMavenCentralRepository
